### PR TITLE
fix: queryCache should not invalidate query when it disabled

### LINKED ISSUE #203: skip option for queries
There is enabled option, but actually "pauses" as written in docs

maybe I'm doing something wrong, but I really need skip option for example via plugin

> use case

I have defined query like this

```ts
export const useGetProject = defineQuery(() => {
  const route = useRoute();
  const projectId = computed(() => route.params.projectId as string);

  const { state, ...rest } = useQuery({
    key: () => [queryKeys.projects, projectId.value],
    query: () => apiGetProject(projectId.value),
    enabled: () => 'projectId' in route.params,
    skip: () => !projectId.value, // request example
  });

  return { ...rest, project: state };
});
```

and also mutation to update project

```ts
export const useUpdateProject = defineMutation({
  mutation: (data: ProjectUpdate) => apiUpdateProject(data),
  onSettled: () => {
    const queryCache = useQueryCache();
    queryCache.invalidateQueries({ key: [queryKeys.projects] });
  },
});
```

and I always getting something like `.../api/projects/undefined/` cause invalidation ignores enabled option

### PR DESCRIPTION
**Pull request by tednaaa**
closes #203

### CODE REVIEW

File: src/query-store.ts [hunk 1]
```diff
@@ -444,7 +444,7 @@ export const useQueryCache = /* @__PURE__ */ defineStore(QUERY_STORE_ID, ({ acti
     return Promise.all(
       getEntries(filters).map((entry) => {
         invalidate(entry)
-        return entry.active && fetch(entry)
+        return entry.active && entry.options?.enabled && fetch(entry)
```
Comment (posva) [inline src/query-store.ts]: Enabled can also be a ref, so we need this

```suggestion
        return entry.active && toValue(entry.options?.enabled) && fetch(entry)
```

File: src/use-query.spec.ts [hunk 2]
```diff
@@ -997,6 +997,19 @@ describe('useQuery', () => {
     expect(query).toHaveBeenCalledTimes(2)
   })
 
+  it('should not invalidate query when enabled is false', async () => {
+    const { query } = mountSimple({ enabled: false })
```
Comment (posva) [inline src/use-query.spec.ts:1001]: let's add another test that has `() => false` and also skips fetching

**Review by posva — CHANGES_REQUESTED** [review]

**Review by posva — APPROVED** [review]
Thanks!
